"""empty message

Revision ID: 6137205f9285
Revises: 19921fc5aaae
Create Date: 2022-08-12 21:09:08.491240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6137205f9285'
down_revision = '19921fc5aaae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'Shows', ['show_id'], ['id'])
    op.drop_constraint('Shows_venue_fkey', 'Shows', type_='foreignkey')
    op.drop_constraint('Shows_artist_id_fkey', 'Shows', type_='foreignkey')
    op.drop_column('Shows', 'venue')
    op.drop_column('Shows', 'artist_id')
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Shows', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    op.add_column('Shows', sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Shows', sa.Column('venue', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Shows_artist_id_fkey', 'Shows', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key('Shows_venue_fkey', 'Shows', 'Venue', ['venue'], ['id'])
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    # ### end Alembic commands ###
